### PR TITLE
Tweak fatal error handling in pontoon-to-webext script

### PR DESCRIPTION
**Pull request by 6a68**
This came up in a Page Shot review that included a copypasta'd pontoon-to-webext.js. Nice idea, thought it seemed worth upstreaming :+1:

### CODE REVIEW

**Comment by 6a68** [comment]
FWIW, Ian also suggested making the `catch` inside `writeFiles` a `fatal` error. That seemed different than a tiny, but nice, refactor, so I've left it out here.

**Comment by bwinton** [comment]
As a side question, should I release pontoon-to-webextension as an npm module of its very own?  I didn't bother, because I figured no-one else would use it, but if it's getting copypasta'd, maybe I can make our lives easier…

**Comment by lmorchard** [comment]
Yeah, if it's turning out to be handy for other WebExtensions, might as well package it up for reuse!

**Comment by 6a68** [comment]
@bwinton Yes! It's a really handy tool. I was hoping it'd get published, especially since there's already a not-quite-as-handy tool published under the mozilla org: https://github.com/mozilla/pontoon-to-json

**Comment by bwinton** [comment]
'K.  I'll do that tomorrow morning, before y'all wake up.  :wink:
(In Paris for a DevTools work week, and heading out to dinner soon..)

**Pull request merged**
