### PR TITLE
Better times

### LINKED ISSUE #418: The customizable time dropdown field wrongly displays 2 borders at its bottom if focused when selecting a past date
[Affected versions]:
- Release 58.0 and up
- Snooze Tabs 1.0.21

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (https://669-15314951-gh.circle-artifacts.com/0/tmp/circle-artifacts.kZdit8p/addon.xpi) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to a website.
2. Click the "Snooze Tabs" button from the toolbar.
3. Click the "Pick a Date/Time" option.
4. Click on the arrow from the left of the current month and year.
5. Click on the "customizable time dropdown" field and observe the way it reacts.

[Expected result]:
- The field is focused correctly.

[Actual result]:
- The field is wrongly focused - there are 2 borders displayed at the bottom of the field.

[Notes]:
- Attached a screen recording of the issue: 

focus

### LINKED ISSUE #475: Is this maintained?
Testpilot ended, but this extension is still on AMO, which is good IMHO, because I really like it.

Howerver, you did not link it from here, which is not so nice.

I've opened https://github.com/bwinton/SnoozeTabs/pull/474 to fix that at least.

However, in general there is the question of whether this is maintained.

If not you can [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

### PR DESCRIPTION
**Pull request by bwinton**
Fixes #418, #475, #476, #486 (kind of).

### CODE REVIEW

**Comment by bwinton** [comment]
@rugk, @gaul, @lmorchard : I know it's been a while, but did any of you want to take a look at this before I merge it? 🙂

**Comment by rugk** [comment]
I'm not a maintainer, but thanks a lot for all the work you've put into this here!

As from https://github.com/bwinton/SnoozeTabs/issues/475#issuecomment-899836827 the main issue was on how to get the build to work, so if you have any documentation to add, I guess that us always appreciated.
The CI also currently fails, BTW… of course that should work, too then. I guess. :slightly_smiling_face:

**Review by rugk — APPROVED** [review]
LGTM. Only one general note for further maintainance: MomentJS is more or less deprecated, as it stands now: https://momentjs.com/docs/#/-project-status/

**Review by gaul — APPROVED** [review]

**Comment by bwinton** [comment]
Good catch on the Moment deprecation. Day.js looks like the easiest replacement, so if we make more changes we should probably switch to that…

**Pull request merged**
