### PR TITLE
fix: Snooze the correct tab from the context menu.

### LINKED ISSUE #88: Snoozed private tabs reopen in non-private tabs if no Private browsing window is open
Found in b31e8b2

---

### Steps to reproduce:
1. Open a regular browsing window.
1. Open a private browsing window and go to http://www.cnn.com.
1. Snooze the private CNN tab to "Real Soon Now!" which should relaunch it after a few seconds.
1. Before the new tab is launched in the private browsing window (created in step 2), close that private browsing session.

### Actual results:
CNN is reopened in the non-private browsing session (created in step 1 above).

### Expected results:
A new Private browsing session browser instance is launched (if one isn't already opened) and the snoozed CNN link is reopened in private browsing mode.

Not sure if we can annotate links as private/public when snoozing them, but we should open them in their pre-snoozed browsing context.

This will be further confused when we also launch [Containers/Spaces](https://github.com/mozilla/testpilot-containers) and user's can have a tab in a Personal/Shopping/Banking tab group. Similarly to the private session above, we should reopen a snoozed "banking" link in their original context.

### LINKED ISSUE #91: Unable to snooze tab to a specific date/time via context menu
Found in bd93684 (via `$ git rev-parse --short HEAD`)

### Steps to reproduce:
1. Launch FF Nightly; `$ ./node_modules/.bin/web-ext run -s dist --firefox=Nightly`
1. Go to a page on The Internets.
1. Right-click the tab and select "Snooze Tab until > Pick a Date/Time".

### Actual results:
Sadness and disappointment. Oh, plus nothing happens. No menus or doorhangers or anything that lets you choose a date/time.

### Expected results:
We need to display a date/time menu since no snooze is currently created.

### LINKED ISSUE #96: Wrong tab is snoozed if you try to snooze an unfocused tab using the context-menu options
[Affected versions]:
- Nightly 53.0a1
- Snooze Tabs 1.0 (built on 1/16/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0-dev, built on 1/16/2017) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to two or more websites(in different tabs).
2. Right-click on an unfocused tab.
3. While observing the tabs choose one of the snoozing options from the context-menu.

[Expected result]:
- The unfocused tab is snoozed and closed while the focused tab remains active.

[Actual result]:
- The focused tab is snoozed and closed while the unfocused tab remains active.

[Notes]:
- This issue also allows the user to snooze special urls (about:newtab, about:debugging, etc.)
- Attached a screen recording of the issue:
snoozetabs_contextmenu_snooze_issue

### PR DESCRIPTION
**Pull request by bwinton**
* Simplify the logic because we know we only have one tab to close.
* Move the 'pick' constant into `times.js`
* Donʼt show the 'pick' option in the context menu.
* Don't show the context menu in private windows.

Fixes #88.
Fixes #91.
Fixes #96.

### CODE REVIEW

**Comment by pdehaan** [comment]
What channels support the context menu? Only Nightly?

**Comment by bwinton** [comment]
Yeah, only nightly, I believe.  It landed in [bug 1316020](https://bugzilla.mozilla.org/show_bug.cgi?id=1316020), if that helps track it down…

**Comment by pdehaan** [comment]
One weird thing with snoozed tabs in private browsing mode, is that if you have existing snoozed tabs and then go into Private Browsing mode, you can restore the snoozed tab which opens in the private browser.

**Comment by pdehaan** [comment]
Not sure if it's directly related to this PR or something else, but you see a slight flicker where you click the SnoozeTabs toolbar button and the "Snooze Tab Until..." dialog quickly animates away and is replaced by the "Manage Snoozed Tabs" dialog:

snuztabs

**Comment by bwinton** [comment]
Fixed in a followup PR.

**Pull request merged**
